# Generated by Django 5.0.6 on 2024-06-04 04:45

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pernyataan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("judul", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("nama", models.CharField(max_length=50)),
                ("nip", models.CharField(blank=True, max_length=18, null=True)),
                ("jabatan", models.CharField(blank=True, max_length=70, null=True)),
                ("passphrase", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("judul", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Submisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("nama", models.CharField(help_text="Nama sesuai KTP", max_length=100)),
                (
                    "nik",
                    models.CharField(
                        help_text="Nomor Induk Kependudukan",
                        max_length=16,
                        unique=True,
                        verbose_name="NIK",
                    ),
                ),
                (
                    "wa",
                    models.CharField(
                        help_text="Nomor WhatsApp (WA) yang bisa dihubungi, diawali 08",
                        max_length=15,
                        unique=True,
                        verbose_name="nomor WA",
                    ),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "pendidikan",
                    models.CharField(
                        choices=[
                            ("d12", "Diploma I/II"),
                            ("d3", "Akademi / Diploma III / Sarjana Muda"),
                            ("s1", "Diploma IV / Sarjana (S1)"),
                            ("s2", "Magister (S2)"),
                            ("s3", "Doktor (S3)"),
                        ],
                        max_length=5,
                        verbose_name="pendidikan terakhir",
                    ),
                ),
                (
                    "afiliasi",
                    models.CharField(
                        blank=True,
                        help_text="Nama institusi atau organisasi afiliasi, jika ada",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "swafoto",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        quality=80,
                        scale=None,
                        size=[None, 480],
                        upload_to="swafoto/",
                    ),
                ),
                (
                    "judul_pb",
                    models.CharField(
                        help_text="Maksimum 200 karakter",
                        max_length=200,
                        verbose_name="judul Policy Brief",
                    ),
                ),
                ("abstrak_pb", models.TextField(verbose_name="abstrak Policy Brief")),
                (
                    "kategori_pendaftar",
                    models.CharField(
                        choices=[("umum", "Umum"), ("mhs", "Mahasiswa")], max_length=10
                    ),
                ),
                (
                    "daftar_anggota",
                    models.TextField(
                        blank=True,
                        help_text="Tuliskan nama-nama anggota tim yang terlibat (jika ada) dipisahkan dengan tanda titik koma (;)",
                        null=True,
                    ),
                ),
                ("lolos_tahap_1", models.BooleanField(default=False)),
                ("lolos_tahap_2", models.BooleanField(default=False)),
                ("lolos_tahap_3", models.BooleanField(default=False)),
                (
                    "file_pb_pdf",
                    models.FileField(blank=True, null=True, upload_to="dokumen_pb/"),
                ),
                (
                    "file_pb_doc",
                    models.FileField(blank=True, null=True, upload_to="dokumen_pb/"),
                ),
                (
                    "file_pb_ppt",
                    models.FileField(blank=True, null=True, upload_to="dokumen_pb/"),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="submisis",
                        to="hp_awards.reviewer",
                    ),
                ),
                (
                    "topik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submisi",
                        to="hp_awards.topik",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
