# Generated by Django 5.0.6 on 2024-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="penilaian",
            name="string_nilai1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="penilaian",
            name="string_nilai2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="penilaian",
            name="string_nilai3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="policy_questions",
            field=models.ManyToManyField(
                help_text="minimal pilih satu",
                related_name="submisis",
                to="hp_awards.policyquestion",
                verbose_name="policy question",
            ),
        ),
    ]
