# Generated by Django 5.0.6 on 2024-06-04 13:21

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pernyataan",
            options={"verbose_name_plural": "Pernyataan"},
        ),
        migrations.AlterModelOptions(
            name="reviewer",
            options={"verbose_name_plural": "Reviewer"},
        ),
        migrations.AlterModelOptions(
            name="submisi",
            options={"verbose_name_plural": "Submisi"},
        ),
        migrations.AlterModelOptions(
            name="topik",
            options={"verbose_name_plural": "Topik"},
        ),
        migrations.AddField(
            model_name="reviewer",
            name="instansi",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="swafoto",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[None, 480],
                upload_to="swafoto/",
                verbose_name="swafoto pendaftar",
            ),
        ),
    ]
