# Generated by Django 5.0.6 on 2024-06-10 01:23

import django.core.validators
import django.db.models.deletion
import django_resized.forms
import hp_awards.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="ktm",
            field=models.FileField(
                blank=True,
                help_text="[format PDF atau JPG/PNG] KTM atau surat keterangan mahasiswa",
                null=True,
                upload_to="ktm/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "bmp"]
                    ),
                    hp_awards.validators.filesize_validator,
                ],
                verbose_name="KTM / surket mahasiswa",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="policy_question",
            field=models.ForeignKey(
                help_text="Pilih Lainnya jika ingin membuat Policy Question baru",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submisis",
                to="hp_awards.policyquestion",
                verbose_name="Policy Question",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="policy_question_custom",
            field=models.CharField(
                blank=True,
                help_text="Anda harus menuliskan Policy Question Anda jika memilih 'LAINNYA'",
                max_length=500,
                null=True,
                verbose_name="Policy Question Anda",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="swafoto",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                help_text="[format JPG atau PNG] rasio 2x3 portrait",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[None, 480],
                upload_to="swafoto/",
                verbose_name="pasfoto penulis utama",
            ),
        ),
    ]
