# Generated by Django 5.0.6 on 2024-06-05 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0003_alter_submisi_abstrak_pb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submisi",
            name="nik",
        ),
    ]
