# Generated by Django 5.0.6 on 2024-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0003_reviewer_kategori"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewer",
            name="kepakaran",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("kemkes", "Pejabat Kementerian Kesehatan"),
                    ("pt", "Perguruan Tinggi"),
                    ("skm", "Staf Khusus Menteri"),
                    ("lan", "LAN"),
                    ("bappenas", "Bappenas"),
                    ("diaspora", "Diaspora"),
                    ("lainnya", "Lainnya"),
                ],
                default="lainnya",
                max_length=70,
            ),
        ),
    ]
