# Generated by Django 5.0.6 on 2024-06-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0004_reviewer_kepakaran_alter_reviewer_kategori"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="kategori_pendaftar",
            field=models.CharField(
                choices=[
                    ("umum", "Umum"),
                    ("mhs", "Mahasiswa S1"),
                    ("mhs2", "Mahasiswa S2"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="pendidikan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("s1", "Sarjana (S1)"),
                    ("s2", "Magister (S2)"),
                    ("s3", "Doktor (S3)"),
                ],
                max_length=5,
                null=True,
                verbose_name="pendidikan terakhir",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="status",
            field=models.CharField(
                choices=[
                    ("tunggu", "Menunggu Verifikasi"),
                    ("review", "Dalam Review"),
                    ("gugur", "Gugur"),
                ],
                default="tunggu",
                max_length=100,
            ),
        ),
    ]
