# Generated by Django 5.0.6 on 2024-06-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0005_alter_submisi_kategori_pendaftar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submisi",
            name="pekerjaan",
            field=models.CharField(
                blank=True,
                help_text="Contoh: analis kebijakan, dosen, peneliti, dsb",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="afiliasi",
            field=models.CharField(
                blank=True,
                help_text="Nama institusi, universitas, atau organisasi afiliasi (jika ada)",
                max_length=150,
                null=True,
                verbose_name="institusi",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="policy_question",
            field=models.ForeignKey(
                help_text="Pilih LAINNYA jika ingin membuat Policy Question baru",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submisis",
                to="hp_awards.policyquestion",
                verbose_name="Policy Question",
            ),
        ),
    ]
