# Generated by Django 5.0.6 on 2024-06-05 06:51

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0005_alter_submisi_abstrak_pb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="pendidikan",
            field=models.CharField(
                choices=[
                    ("d12", "Diploma I/II"),
                    ("d3", "Akademi / Diploma III / Sarjana Muda"),
                    ("s1", "Diploma IV / Sarjana (S1)"),
                    ("s2", "Magister (S2)"),
                    ("s3", "Doktor (S3)"),
                ],
                help_text="Mahasiswa S3 harus memilih Kategori Umum",
                max_length=5,
                verbose_name="pendidikan terakhir",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="swafoto",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[None, 480],
                upload_to="swafoto/",
                verbose_name="pasfoto pendaftar",
            ),
        ),
    ]
