# Generated by Django 5.0.6 on 2024-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0006_alter_submisi_pendidikan_alter_submisi_swafoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="kategori_pendaftar",
            field=models.CharField(
                choices=[("umum", "Umum"), ("mhs", "Mahasiswa")],
                help_text="Mahasiswa S3 harus memilih Kategori Umum",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="pendidikan",
            field=models.CharField(
                choices=[
                    ("d12", "Diploma I/II"),
                    ("d3", "Akademi / Diploma III / Sarjana Muda"),
                    ("s1", "Diploma IV / Sarjana (S1)"),
                    ("s2", "Magister (S2)"),
                    ("s3", "Doktor (S3)"),
                ],
                max_length=5,
                verbose_name="pendidikan terakhir",
            ),
        ),
    ]
