# Generated by Django 5.0.6 on 2024-06-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0006_submisi_pekerjaan_alter_submisi_afiliasi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="pekerjaan",
            field=models.CharField(
                blank=True,
                help_text="Contoh: analis kebijakan, dosen, peneliti, dsb",
                max_length=150,
                null=True,
                verbose_name="profesi",
            ),
        ),
    ]
