# Generated by Django 5.0.6 on 2024-06-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0007_alter_submisi_pekerjaan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penilaian",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penilaians",
                to="hp_awards.reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="kategori_pendaftar",
            field=models.CharField(
                choices=[
                    ("umum", "Umum"),
                    ("mhs", "Mahasiswa"),
                    ("mhs2", "Mahasiswa S2"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="wa",
            field=models.CharField(
                help_text="Nomor WhatsApp (WA) yang bisa dihubungi, diawali 08",
                max_length=15,
                verbose_name="nomor WA",
            ),
        ),
    ]
