# Generated by Django 5.0.6 on 2024-06-06 01:02

import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0007_alter_submisi_kategori_pendaftar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submisi",
            name="kode_submisi",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="abstrak_pb",
            field=models.TextField(
                help_text="Maksimum 250 kata", verbose_name="abstrak Policy Brief"
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="swafoto",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                help_text="rasio 2x3 portrait",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[None, 480],
                upload_to="swafoto/",
                verbose_name="pasfoto pendaftar",
            ),
        ),
    ]
