# Generated by Django 5.0.6 on 2024-06-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0008_submisi_kode_submisi_alter_submisi_abstrak_pb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submisi",
            name="status",
            field=models.CharField(
                choices=[("tunggu", "Menunggu Penilaian"), ("gugur", "Gugur")],
                default="tunggu",
                max_length=100,
            ),
        ),
    ]
