# Generated by Django 5.0.6 on 2024-06-12 13:40

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0008_alter_penilaian_reviewer_alter_submisi_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="swafoto",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                help_text="[format JPG atau PNG] rasio 2x3 portrait",
                keep_meta=True,
                null=True,
                quality=80,
                scale=None,
                size=[None, 480],
                upload_to="swafoto/",
                verbose_name="pasfoto penulis utama",
            ),
        ),
    ]
