# Generated by Django 5.0.6 on 2024-06-06 04:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0009_submisi_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kolaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("nama", models.CharField(max_length=100)),
                (
                    "wa",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="nomor WA"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("jabatan", models.CharField(blank=True, max_length=100, null=True)),
                ("peran", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="reviewer",
            name="kode_reviewer",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="reviewer",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="passphrase",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=6,
                verbose_name="kata sandi",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="submisi",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="submisis", to="hp_awards.reviewer"
            ),
        ),
        migrations.AddField(
            model_name="submisi",
            name="kolaborators",
            field=models.ManyToManyField(
                blank=True, related_name="submisis", to="hp_awards.kolaborator"
            ),
        ),
    ]
