# Generated by Django 5.0.6 on 2024-06-12 15:42

import django.core.validators
import hp_awards.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0009_alter_submisi_swafoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submisi",
            name="afiliasi",
            field=models.CharField(
                blank=True,
                help_text="Nama institusi/organisasi, atau universitas (bagi mahasiswa)",
                max_length=150,
                null=True,
                verbose_name="institusi",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="ktm",
            field=models.FileField(
                blank=True,
                help_text="[format PDF atau JPG/PNG] Untuk mahasiswa, melampirkan bukti atau pernyataan sebagai mahasiswa",
                null=True,
                upload_to="ktm/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "bmp"]
                    ),
                    hp_awards.validators.filesize_validator,
                ],
                verbose_name="KTM / surket mahasiswa",
            ),
        ),
    ]
