# Generated by Django 5.0.6 on 2024-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hp_awards",
            "0010_kolaborator_reviewer_kode_reviewer_reviewer_username_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kolaborator",
            options={"verbose_name_plural": "Kolaborator"},
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="nip",
            field=models.CharField(
                blank=True,
                help_text="Maks. 18 karakter",
                max_length=18,
                null=True,
                verbose_name="NIP/NIK/ID lainnya",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="file_pb_doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dokumen_pb/",
                verbose_name="file PB DOC",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="file_pb_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dokumen_pb/",
                verbose_name="file PB PDF",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="file_pb_ppt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dokumen_pb/",
                verbose_name="file PB PPT",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="kolaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="submisis",
                to="hp_awards.kolaborator",
                verbose_name="kolaborators",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="submisis",
                to="hp_awards.reviewer",
                verbose_name="reviewer",
            ),
        ),
    ]
