# Generated by Django 5.0.6 on 2024-06-25 08:33

import django.core.validators
import hp_awards.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0011_alter_submisi_afiliasi_alter_submisi_ktm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kolaborator",
            name="email",
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="kolaborator",
            name="wa",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="nomor WA"
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="ktm",
            field=models.FileField(
                blank=True,
                help_text="[format PDF atau JPG/PNG] Bukti atau pernyataan sebagai mahasiswa aktif",
                null=True,
                upload_to="ktm/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "docx",
                            "doc",
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "bmp",
                        ]
                    ),
                    hp_awards.validators.filesize_validator,
                ],
                verbose_name="KTM / surat pernyataan",
            ),
        ),
        migrations.AlterField(
            model_name="submisi",
            name="status",
            field=models.CharField(
                choices=[
                    ("tunggu", "Menunggu Review"),
                    ("review", "Dalam Review"),
                    ("gugur", "Gugur"),
                ],
                default="tunggu",
                max_length=100,
            ),
        ),
    ]
