# Generated by Django 5.0.6 on 2024-06-06 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0011_alter_kolaborator_options_alter_reviewer_nip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penilaian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("nilai1", models.IntegerField(default=0)),
                ("nilai2", models.IntegerField(default=0)),
                ("nilai3", models.IntegerField(default=0)),
                ("komentar", models.TextField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hp_awards.reviewer",
                    ),
                ),
                (
                    "submisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hp_awards.submisi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
