# Generated by Django 5.0.6 on 2024-07-09 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0012_alter_kolaborator_email_alter_kolaborator_wa_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submisi",
            options={
                "permissions": [("change_manage_submissions", "Bisa mengatur submisi")],
                "verbose_name_plural": "Submisi",
            },
        ),
    ]
