# Generated by Django 5.0.6 on 2024-06-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0012_penilaian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penilaian",
            name="submisi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penilaians",
                to="hp_awards.submisi",
            ),
        ),
    ]
