# Generated by Django 5.0.6 on 2024-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hp_awards", "0013_alter_submisi_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="penilaian",
            options={"verbose_name": "Penilaian", "verbose_name_plural": "Penilaian"},
        ),
        migrations.AddField(
            model_name="submisi",
            name="file_turnitin",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dokumen_turnitin/",
                verbose_name="file Turnitin",
            ),
        ),
    ]
